### ISSUE TITLE
retrieving map locks up

### ISSUE THREAD

**Issue by beefydog** [burakoner/CoinMarketCapApi#1]
The CryptoCurrencyMap function locks up when called:

Example trying to make a call (for 2 records, in this case) like so, simply locks up the application

`            var cli = new CoinMarketCap.ProClient("*************");
          var map =   cli.CryptocurrencyMap(listing_status: ListingStatus.active,1,2); `

**Comment by burakoner** [comment]
Did you try using in different tread?
